name: Build, Push Docker Image and Deploy Infrastructure
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_SERVER }}
        username: ${{ fromJson(secrets.AZURE_CREDENTIALS).appId }}
        password: ${{ fromJson(secrets.AZURE_CREDENTIALS).password }}
        
    - name: Build and push Docker image to ACR
      uses: docker/build-push-action@v2
      with:
        context: .
        file: infra/dockerfile
        push: true
        tags: ${{ secrets.ACR_SERVER }}/petersoncommondataservice:latest
        
    # Terraform steps
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0
        
    - name: Azure Login for Terraform
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Terraform Init
      run: |
        cd infra/terraform
        terraform init -backend-config="storage_account_name=${{ secrets.TF_STORAGE_ACCOUNT }}" \
                       -backend-config="container_name=${{ secrets.TF_CONTAINER }}" \
                       -backend-config="key=${{ secrets.TF_STATE_KEY }}" \
                       -backend-config="use_azuread_auth=true" \
                       -backend-config="subscription_id=${{ fromJson(secrets.AZURE_CREDENTIALS).subscriptionId }}" \
                       -backend-config="tenant_id=${{ fromJson(secrets.AZURE_CREDENTIALS).tenantId }}" \
                       -backend-config="client_id=${{ fromJson(secrets.AZURE_CREDENTIALS).appId }}" \
                       -backend-config="client_secret=${{ fromJson(secrets.AZURE_CREDENTIALS).password }}"
      
    - name: Terraform Plan
      run: |
        cd infra/terraform
        terraform plan -var="ics_url=${{ secrets.ICS_URL }}" \
                       -var="todoist_api_key=${{ secrets.TODOIST_API_KEY }}" \
                       -var="todoist_project_id=${{ secrets.TODOIST_PROJECT_ID }}" \
                       -var="container_app_name=petersoncommondataservice" \
                       -out=tfplan
                       
    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: |
        cd infra/terraform
        terraform apply -auto-approve tfplan